import assert from 'node:assert/strict';
import test from 'node:test';
import {registerHooks} from 'node:module';
import {IDBFactory} from 'fake-indexeddb';
registerHooks({resolve(specifier,context,next){try{return next(specifier,context)}catch(error){if(specifier.startsWith('.'))return next(specifier+'.ts',context);throw error}}});
const {readStoredAccountBinding}=await import('../src/utils/accountStorageBootstrap.ts');
const a={project:'https://project.supabase.co',userId:'account-a',syncId:'a'.repeat(36)};
async function open(factory,name,version,upgrade){return new Promise((resolve,reject)=>{const request=factory.open(name,version);request.onupgradeneeded=()=>upgrade?.(request.result,request.transaction);request.onsuccess=()=>resolve(request.result);request.onerror=()=>reject(request.error)})}
async function populate(factory,name,values){const db=await open(factory,name,7,db=>{db.createObjectStore('appRecordMeta');db.createObjectStore('questionImageBlobs')});await new Promise((resolve,reject)=>{const tx=db.transaction(['appRecordMeta','questionImageBlobs'],'readwrite');for(const [key,value]of Object.entries(values))tx.objectStore('appRecordMeta').put(value,key);tx.objectStore('questionImageBlobs').put(new Blob(['unchanged image']),'image');tx.oncomplete=resolve;tx.onabort=()=>reject(tx.error)});db.close()}
test('missing legacy DB remains missing instead of becoming an empty upgraded database',async()=>{const factory=new IDBFactory();assert.equal(await readStoredAccountBinding(factory,'missing'),null);assert.deepEqual(await factory.databases(),[])});
test('a metadata read preserves schema version, frozen request, cursor and blob bytes',async()=>{const factory=new IDBFactory(),batch={connection:a,operations:[{operationId:'preserved-id',raw:'preserved bytes'}]};await populate(factory,'legacy',{recordSyncConnection:a,pushBatch:batch,pullCursor:{connection:a,cursor:15}});assert.deepEqual(await readStoredAccountBinding(factory,'legacy'),a);const db=await open(factory,'legacy');assert.equal(db.version,7);const tx=db.transaction(['appRecordMeta','questionImageBlobs']),batchRead=tx.objectStore('appRecordMeta').get('pushBatch'),image=tx.objectStore('questionImageBlobs').get('image');await new Promise(resolve=>{tx.oncomplete=resolve});assert.deepEqual(batchRead.result,batch);assert.equal(await image.result.text(),'unchanged image');db.close()});
test('a frozen request can establish a consistent local binding without changing it',async()=>{const factory=new IDBFactory();await populate(factory,'legacy',{pushBatch:{connection:a,operations:[]},pullStage:{connection:a}});assert.deepEqual(await readStoredAccountBinding(factory,'legacy'),a)});
test('mixed accounts, different IDs and malformed metadata fail closed with originals intact',async()=>{for(const other of [{...a,userId:'account-b'},{...a,syncId:'b'.repeat(36)},{...a,syncId:'weak'},{}]){const factory=new IDBFactory();await populate(factory,'legacy',{recordSyncConnection:a,pushBatch:{connection:other}});await assert.rejects(readStoredAccountBinding(factory,'legacy'));const db=await open(factory,'legacy');assert.equal(db.version,7);db.close()}});
