import assert from 'node:assert/strict';
import test from 'node:test';
import { IDBFactory, IDBKeyRange } from 'fake-indexeddb';
globalThis.IDBKeyRange = IDBKeyRange;
import { AccountStorageSession, accountGenerationKey, decideAccountStorage } from '../src/utils/accountStorage.ts';
import { APP_COLLECTIONS, appRecordKey, readAppRecordSnapshot, materializeAppRecords } from '../src/utils/appRecordStorage.ts';
import { normalizeAppData } from '../src/utils/appDataValidation.ts';
import { createUnionMigration, previewUnionMigration, saveUnionChoices, readUnionMigrations, prepareUnionMigration, activateUnionMigration, rollbackUnionMigration, openUnionStage } from '../src/utils/accountUnionJournal.ts';
import { remapUnionWork } from '../src/utils/accountUnionWork.ts';
const identity={project:'https://union-qa.invalid',userId:'owner'},stamp='2026-10-05T00:00:00.000Z';
function memory(){const values=new Map();return {get length(){return values.size},key:i=>[...values.keys()][i]??null,getItem:k=>values.get(k)??null,setItem:(k,v)=>values.set(k,String(v)),removeItem:k=>values.delete(k),clear:()=>values.clear()};}
function snapshot(prefix,kind='local'){const f=prefix+'-f',s=prefix+'-s',q=prefix+'-q',app=normalizeAppData({version:1,folders:[{id:f,name:prefix,createdAt:stamp,updatedAt:stamp}],problemSets:[{id:s,folderId:f,title:prefix,source:'',createdAt:stamp,updatedAt:stamp}],questions:[{id:q,setId:s,question:prefix,choices:['A','B','C','D'],answerIndex:0,answerText:'A',explanation:'',sourcePage:'',category:'',difficulty:'standard',createdAt:stamp,updatedAt:stamp}],progress:[],answerLogs:[]}).data;return {identity,label:prefix,kind,...(kind==='cloud'?{syncId:'a'.repeat(36)}:{}),head:1,records:APP_COLLECTIONS.flatMap(collection=>app[collection].map((value,position)=>{const id=collection==='progress'?value.questionId:value.id;return{key:appRecordKey(collection,id),collection,id,raw:JSON.stringify(value),position,revision:kind==='cloud'?1:0}}))};}
async function fixture(){const native=memory(),factory=new IDBFactory(),owner=new AccountStorageSession(native,decideAccountStorage(native,identity,null)),local=snapshot('phone'),destination=snapshot('pc','cloud');owner.storage.setItem('quiz-make-app-data-v1','phone-original');owner.storage.setItem('quizMake:studyTimeZone','Etc/UTC');const assertCurrent=()=>owner.assertCurrent();const entry=await createUnionMigration(factory,native,owner,local,destination,[local],assertCurrent);const deps={assertCurrent,readLocal:async()=>structuredClone(local),recheckCloud:async()=>{},readImage:()=>assert.fail('no images')};return{native,factory,owner,local,destination,entry,deps};}
test('dry run saves exact originals but does not change active data; staging/restart/activation retain both sides and canonical CAS bases',async()=>{
  const f=await fixture();assert.equal(f.native.getItem(accountGenerationKey(identity)),null);assert.equal(f.owner.storage.getItem('quiz-make-app-data-v1'),'phone-original');assert.equal(previewUnionMigration(f.entry).data.problemSets.length,2);
  const prepared=await prepareUnionMigration(f.factory,f.native,f.entry,f.deps);assert.equal(f.native.getItem(accountGenerationKey(identity)),null);assert.equal(f.owner.storage.getItem('quiz-make-app-data-v1'),'phone-original');const resumed=(await readUnionMigrations(f.factory,f.native,identity))[0];assert.equal(resumed.phase,'prepared');assert.deepEqual(resumed.destination,f.destination);assert.deepEqual(resumed.sources[0],f.local);
  await activateUnionMigration(f.factory,f.native,resumed,f.deps);assert.equal(f.native.getItem(accountGenerationKey(identity)),prepared.generation);assert.throws(()=>f.owner.storage.setItem('quizMake:plan:late','stale'),/移行状態/);
  const active=new AccountStorageSession(f.native,decideAccountStorage(f.native,identity,null)),db=await openUnionStage(f.factory,active);try{const snapshot=await readAppRecordSnapshot(db);assert.equal(materializeAppRecords(snapshot).questions.length,2);const tx=db.transaction(['appOutbox','appRecordMeta']),ops=tx.objectStore('appOutbox').getAll(),connection=tx.objectStore('appRecordMeta').get('recordSyncConnection');await new Promise(r=>tx.oncomplete=r);assert.ok(ops.result.length>0);assert.ok(ops.result.every(op=>op.baseRevision===0));assert.equal(connection.result.syncId,f.destination.syncId);assert.equal(active.storage.getItem('quizMake:sync:recordV2OptIn'),f.destination.syncId);}finally{db.close();}
  assert.equal((await readUnionMigrations(f.factory,f.native,identity))[0].phase,'activated');const other=new AccountStorageSession(f.native,decideAccountStorage(f.native,{...identity,userId:'other'},null));assert.equal(other.storage.getItem('quiz-make-app-data-v1'),null);
});
test('local/remote changes, account changes and failed shadow writes stop before activation and preserve originals',async()=>{
  for(const mode of ['local','remote','account','settings','storage','ignored-storage']){const f=await fixture(),deps={...f.deps};if(mode==='local')deps.readLocal=async()=>({...f.local,label:'changed'});if(mode==='remote')deps.recheckCloud=async()=>{throw Error('remote changed')};if(mode==='account')deps.assertCurrent=()=>{throw Error('account changed')};if(mode==='settings')f.owner.storage.setItem('quiz-make:companion-enabled','off');if(mode==='storage')f.native.setItem=()=>{throw new DOMException('quota','QuotaExceededError')};if(mode==='ignored-storage')f.native.setItem=()=>{};
    await assert.rejects(prepareUnionMigration(f.factory,f.native,f.entry,deps));assert.equal(f.native.getItem(accountGenerationKey(identity)),null);assert.equal(f.owner.storage.getItem('quiz-make-app-data-v1'),'phone-original');assert.deepEqual((await readUnionMigrations(f.factory,f.native,identity))[0].sources[0],f.local);
  }
});
test('restart after activation is inferred from pointer even when journal receipt is lost; rollback leaves cloud and new generation intact',async()=>{
  const f=await fixture(),prepared=await prepareUnionMigration(f.factory,f.native,f.entry,f.deps);f.native.setItem(accountGenerationKey(identity),prepared.generation);const resumed=(await readUnionMigrations(f.factory,f.native,identity))[0];assert.equal(resumed.phase,'activated');await rollbackUnionMigration(f.factory,f.native,resumed,()=>{});assert.equal(f.native.getItem(accountGenerationKey(identity)),null);assert.equal(f.owner.storage.getItem('quiz-make-app-data-v1'),'phone-original');assert.deepEqual((await readUnionMigrations(f.factory,f.native,identity))[0].destination,f.destination);assert.equal((await readUnionMigrations(f.factory,f.native,identity))[0].phase,'rolled_back');
});
test('new learning or uncertain sends after migration block rollback rather than discard new data',async()=>{
  for(const mode of ['answer','batch','stage']){const f=await fixture(),prepared=await prepareUnionMigration(f.factory,f.native,f.entry,f.deps);await activateUnionMigration(f.factory,f.native,prepared,f.deps);const activated=(await readUnionMigrations(f.factory,f.native,identity))[0],active=new AccountStorageSession(f.native,decideAccountStorage(f.native,identity,null)),db=await openUnionStage(f.factory,active),tx=db.transaction(['appRecords','appRecordMeta'],'readwrite');if(mode==='answer'){const req=tx.objectStore('appRecords').get(appRecordKey('questions','phone-q'));req.onsuccess=()=>tx.objectStore('appRecords').put({...req.result,raw:JSON.stringify({...JSON.parse(req.result.raw),question:'Edited after union'})},req.result.key);}else tx.objectStore('appRecordMeta').put({newData:true},mode==='batch'?'pushBatch':'pullStage');await new Promise(r=>tx.oncomplete=r);db.close();await assert.rejects(rollbackUnionMigration(f.factory,f.native,activated,()=>{}),/巻き戻しを止め/);assert.equal(f.native.getItem(accountGenerationKey(identity)),prepared.generation);}
});
test('two tabs cannot silently overwrite choices and corrupt cross-account journals or active-generation targets fail closed',async()=>{
  const f=await fixture();const a=await saveUnionChoices(f.factory,f.entry,{},f.deps.assertCurrent);await assert.rejects(saveUnionChoices(f.factory,f.entry,{},f.deps.assertCurrent),/別の画面/);assert.equal((await readUnionMigrations(f.factory,f.native,identity))[0].revision,a.revision);
  await assert.rejects(prepareUnionMigration(f.factory,f.native,{...a,destination:{...a.destination,identity:{...identity,userId:'other'}}},f.deps),/別のアカウント/);
  await assert.rejects(prepareUnionMigration(f.factory,f.native,{...a,previousGeneration:a.generation},f.deps),/所有記録/);assert.equal(f.native.getItem(accountGenerationKey(identity)),null);
  const prepared=await prepareUnionMigration(f.factory,f.native,a,f.deps);await assert.rejects(prepareUnionMigration(f.factory,f.native,f.entry,f.deps),/別の画面/);await assert.rejects(activateUnionMigration(f.factory,f.native,{...prepared,revision:prepared.revision-1},f.deps),/別の画面/);await activateUnionMigration(f.factory,f.native,prepared,f.deps);await assert.rejects(rollbackUnionMigration(f.factory,f.native,prepared,()=>{}),/別の画面/);assert.equal(f.native.getItem(accountGenerationKey(identity)),prepared.generation);
});
test('work checkpoints remap only question references and retain frozen content, answer IDs, plans and actual File bytes',async()=>{
  const file=new File([new Uint8Array([1,255,3])],'original.png',{type:'image/png',lastModified:123}),work={screen:{name:'questionEdit',questionId:'old'},quiz:{questions:[{id:'old',setId:'set',choices:['old','B'],question:'Frozen old question'}],questionIds:['old']},plan:{targetIds:['old'],baselineLogIds:['old'],goal:20,timeZone:'Etc/UTC'},answer:{id:'old',questionId:'old'},file};
  const copy=remapUnionWork(work,{old:'new'});assert.equal(copy.screen.questionId,'new');assert.equal(copy.quiz.questions[0].id,'new');assert.equal(copy.quiz.questions[0].question,'Frozen old question');assert.equal(copy.quiz.questions[0].choices[0],'old');assert.equal(copy.answer.id,'old');assert.deepEqual(copy.plan.baselineLogIds,['old']);assert.equal(copy.plan.goal,20);assert.equal(copy.plan.timeZone,'Etc/UTC');assert.equal(copy.file,file);assert.deepEqual([...new Uint8Array(await copy.file.arrayBuffer())],[1,255,3]);assert.equal(copy.file.lastModified,123);assert.equal(work.screen.questionId,'old');
});
