import assert from 'node:assert/strict';
import test from 'node:test';
import { verifiedCloudAccess, cloudAccessFailureCode, watchCloudSession } from '../src/utils/cloudAuthAccess.ts';
const session=(id='A',token='A-token',expires_at=9999999999)=>({user:{id,is_anonymous:false},access_token:token,refresh_token:'fixture-refresh',expires_at});
const result=(s,error=null)=>({data:{session:s},error});
const user=(id='A',error=null)=>({data:{user:error?null:{id,is_anonymous:false}},error});
function fixture(){let current=session();const calls={tokens:[],refresh:0,guards:[]};const auth={getSession:async()=>result(current),getUser:async token=>{calls.tokens.push(token);return user()},refreshSession:async()=>{calls.refresh++;current=session('A','new-A-token');return result(current)}};return {auth,calls,get current(){return current},set current(v){current=v},guard:id=>calls.guards.push(id),cached:()=>current?.user.id??null};}
test('temporary Auth user/refresh transport failures are retryable and never request login or return a Bearer token',async()=>{
  for(const error of [{name:'AuthRetryableFetchError',status:0},{name:'AuthRetryableFetchError',status:503},{status:429},new TypeError('fixture network failure')]){
    const f=fixture();f.auth.getUser=async()=>user('A',error);const outcome=await verifiedCloudAccess(f.auth,f.guard,f.cached);assert.equal(outcome.reason,'temporarily-unavailable');assert.equal(cloudAccessFailureCode(outcome.reason),'network');assert.equal('accessToken'in outcome,false);assert.equal(f.current.user.id,'A');assert.equal(f.calls.refresh,0);
  }
});
test('SDK session refresh error preserves the known account and is not signed-out authentication_required',async()=>{const f=fixture();f.auth.getSession=async()=>result(null,{name:'AuthRetryableFetchError',status:503});assert.equal((await verifiedCloudAccess(f.auth,f.guard,()=> 'A')).reason,'temporarily-unavailable');assert.deepEqual(f.calls.tokens,[])});
test('same-account token rotation during validation verifies the replacement exact token before sending it',async()=>{const f=fixture();f.auth.getUser=async token=>{f.calls.tokens.push(token);if(token==='A-token')f.current=session('A','rotated-A');return user()};const access=await verifiedCloudAccess(f.auth,f.guard,f.cached);assert.equal(access.ok,true);assert.equal(access.accessToken,'rotated-A');assert.deepEqual(f.calls.tokens,['A-token','rotated-A']);});
test('a rejected old token can be replaced by an already-refreshed same-account token',async()=>{const f=fixture();f.auth.getUser=async token=>{f.calls.tokens.push(token);if(token==='A-token'){f.current=session('A','rotated-A');return user('A',{status:401,code:'bad_jwt'})}return user()};const access=await verifiedCloudAccess(f.auth,f.guard,f.cached);assert.equal(access.accessToken,'rotated-A');assert.equal(f.calls.refresh,0)});
test('an expired access token is refreshed once and its exact replacement is verified without logout',async()=>{const f=fixture();f.current=session('A','expired-A',1);f.auth.getUser=async token=>{f.calls.tokens.push(token);return token==='expired-A'?user('A',{status:401,code:'bad_jwt'}):user()};const access=await verifiedCloudAccess(f.auth,f.guard,f.cached,()=>2000);assert.equal(access.accessToken,'new-A-token');assert.equal(f.calls.refresh,1);assert.deepEqual(f.calls.tokens,['expired-A','new-A-token'])});
test('failed expired-token refresh stays retryable without calling any logout function',async()=>{const f=fixture();f.current=session('A','expired-A',1);f.auth.getUser=async()=>user('A',{status:401,code:'bad_jwt'});f.auth.refreshSession=async()=>result(null,{name:'AuthRetryableFetchError',status:503});assert.equal((await verifiedCloudAccess(f.auth,f.guard,f.cached,()=>2000)).reason,'temporarily-unavailable');assert.equal(f.current.user.id,'A')});
test('actual signed-out, anonymous and rejected sessions remain denied',async()=>{const f=fixture();f.current=null;assert.equal((await verifiedCloudAccess(f.auth,f.guard,f.cached)).reason,'signed-out');f.current={...session(),user:{id:'A',is_anonymous:true}};assert.equal((await verifiedCloudAccess(f.auth,f.guard,f.cached)).reason,'signed-out');f.current=session();f.auth.getUser=async()=>user('A',{status:401,code:'session_not_found'});assert.equal((await verifiedCloudAccess(f.auth,f.guard,f.cached)).reason,'validation-failed');assert.equal(f.calls.refresh,0)});
test('a temporary same-account null read is re-read, but persistent null never authorizes from cache',async()=>{const f=fixture();let count=0;f.auth.getSession=async()=>result(++count===1?null:f.current);assert.equal((await verifiedCloudAccess(f.auth,f.guard,()=> 'A')).ok,true);f.auth.getSession=async()=>result(null);const access=await verifiedCloudAccess(f.auth,f.guard,()=> 'A');assert.equal(access.reason,'temporarily-unavailable');assert.equal('accessToken'in access,false)});
test('A to B change during token verification never acquires B credentials for A work',async()=>{const f=fixture();f.auth.getUser=async token=>{f.calls.tokens.push(token);f.current=session('B','B-token');return user()};assert.equal((await verifiedCloudAccess(f.auth,f.guard,f.cached)).reason,'account-changed');assert.deepEqual(f.calls.tokens,['A-token'])});
test('account change following transient null is also fenced',async()=>{const f=fixture();let count=0;f.auth.getSession=async()=>result(++count===1?null:session('B','B-token'));assert.equal((await verifiedCloudAccess(f.auth,f.guard,()=> 'A')).reason,'account-changed');assert.deepEqual(f.calls.tokens,[])});
test('local ownership guard failures are connection_changed rather than login failures',async()=>{const f=fixture();const access=await verifiedCloudAccess(f.auth,()=>{throw Error('fixture local ownership failure')},f.cached);assert.equal(access.reason,'account-changed');assert.equal(cloudAccessFailureCode(access.reason),'connection_changed');assert.deepEqual(f.calls.tokens,[])});
test('repeated token rotation is bounded and does not send an unverified snapshot',async()=>{const f=fixture();let count=0;f.auth.getUser=async()=>{f.current=session('A','rotated-'+(++count));return user()};assert.equal((await verifiedCloudAccess(f.auth,f.guard,f.cached)).reason,'temporarily-unavailable');assert.equal(count,3)});
function observer(){let cached=session(),event,resolve,reject;const values=[];const stop=watchCloudSession({cached:()=>cached,read:()=>new Promise((r,j)=>{resolve=r;reject=j}),subscribe:fn=>{event=fn;return()=>{event=null}},emit:s=>values.push(s?.user.id??null)});return {values,stop,resolve:s=>resolve(s),reject:e=>reject(e),event:(e,s)=>event?.(e,s),set cached(v){cached=v}};}
const settle=async()=>{for(let i=0;i<5;i++)await Promise.resolve()};
test('UI initial read cannot overwrite a newer Auth event and temporary same-account null events are preserved',async()=>{const f=observer();f.event('TOKEN_REFRESHED',session());f.resolve(null);await settle();assert.deepEqual(f.values,['A','A']);f.event('TOKEN_REFRESHED',null);assert.deepEqual(f.values,['A','A']);f.stop()});
test('UI transient session fetch errors keep cached display only, while explicit signout is honored',async()=>{const f=observer();f.reject(Error('fixture offline'));await settle();assert.deepEqual(f.values,['A']);f.event('SIGNED_OUT',null);assert.deepEqual(f.values,['A',null]);f.stop()});
test('UI changed-account events win over an old pending initial snapshot',async()=>{const f=observer();f.cached=session('B','B-token');f.event('SIGNED_IN',session('B','B-token'));f.resolve(session());await settle();assert.deepEqual(f.values,['A','B']);f.stop()});
test('unmounted UI does not accept pending session results',async()=>{const f=observer();f.stop();f.resolve(session('B','B-token'));await settle();assert.deepEqual(f.values,['A'])});
