import {useEffect,useRef,useState} from 'react';
import type {AppData} from '../types';
import {Layout} from '../components/Layout';
import {BackButton} from '../components/BackButton';
import {SearchIcon,ChevronRightIcon} from '../components/UiIcons';
import {PublicDialog} from '../components/PublicDialog';
import {PublicLibraryRow,LibraryArtwork,LibraryTags,LibraryCounts} from '../components/PublicLibraryRows';
import {SharedQuestionPreview} from '../components/SharedSetDetail';
import {GroupEmpty} from '../components/GroupLearningUi';
import {PublicationJobs} from '../components/PublicationJobs';
import {usePublicationQueue} from '../hooks/usePublicationQueue';
import {cloudConfigured,onCloudSessionSnapshot,getCloudSession,getSharedProblemSet,getCloudDisplayName,type CloudPublishResult} from '../utils/cloudService';
import {readMyPublicLibrary,readPublicFolder,searchPublicLibrary,managePublicFolder,setStandalonePublic,recordPublicImport,fullPublicFolder} from '../utils/publicLibraryService';
import {initialPublicFilters,uniquePublicSets,type PublicFilters,type PublicFolder,type PublicSet} from '../utils/publicLibrary';
import {prepareLocalPublication} from '../utils/publicationPayload';
import {folderSubtreeIds} from '../utils/folderHierarchy';
import type {planPublicImport} from '../utils/publicImport';
import './PublicDiscoveryScreen.css';

interface Props{
  data:AppData;mine?:boolean;folderId?:string;setId?:string;routeTitle?:string;onBack:()=>void;onMine:()=>void;onFolder:(id:string,title?:string)=>void;onSet:(id:string,title?:string)=>void;onLogin:()=>void;
  onPublished:(id:string,result:CloudPublishResult)=>Promise<void>;onImport:(sets:PublicSet[],options:Parameters<typeof planPublicImport>[2])=>Promise<ReturnType<typeof planPublicImport>>;onOpenLocalSet:(id:string)=>void;
}
type PublishForm={kind:'folder'|'set';localId:string;category:string;description:string;tags:string;destination?:PublicFolder};
export function PublicDiscoveryScreen(props:Props){
  const {data}=props;
  const screenRoot=useRef<HTMLDivElement>(null);
  useEffect(()=>{if(screenRoot.current?.parentElement)screenRoot.current.parentElement.scrollTop=0;},[props.mine,props.folderId,props.setId]);
  const [userId,setUserId]=useState(''),userRef=useRef('');
  const [query,setQuery]=useState(''),[filters,setFilters]=useState<PublicFilters>(initialPublicFilters),[draft,setDraft]=useState<PublicFilters|null>(null);
  const [folders,setFolders]=useState<PublicFolder[]>([]),[sets,setSets]=useState<PublicSet[]>([]),[categories,setCategories]=useState<string[]>([]),[offset,setOffset]=useState(0),[more,setMore]=useState(false);
  const [myFolders,setMyFolders]=useState<PublicFolder[]>([]),[mySets,setMySets]=useState<PublicSet[]>([]),[mineKind,setMineKind]=useState<'folder'|'set'>('folder');
  const [folder,setFolder]=useState<PublicFolder|null>(null),[detail,setDetail]=useState<PublicSet|null>(null),[memberSort,setMemberSort]=useState<'new'|'popular'|'updated'>('new');
  const [loading,setLoading]=useState(false),[busy,setBusy]=useState(false),lock=useRef(false),[error,setError]=useState(''),[notice,setNotice]=useState(''),[refresh,setRefresh]=useState(0);
  const [publishChoice,setPublishChoice]=useState(false),[form,setForm]=useState<PublishForm|null>(null),[edit,setEdit]=useState<PublicFolder|null>(null),[editTags,setEditTags]=useState(''),[menu,setMenu]=useState<PublicFolder|PublicSet|null>(null),[confirmation,setConfirmation]=useState<{label:string;run:()=>Promise<void>}|null>(null);
  const [importTarget,setImportTarget]=useState<PublicFolder|PublicSet|null>(null),[targetFolder,setTargetFolder]=useState(''),[newFolderName,setNewFolderName]=useState('');
  const queue=usePublicationQueue(userId,props.onPublished),queueWasRunning=useRef(false),requestEpoch=useRef(0);
  const reload=()=>{setOffset(0);setRefresh(n=>n+1);};
  useEffect(()=>onCloudSessionSnapshot(snapshot=>{const id=snapshot?.user.id??'';if(id!==userRef.current){requestEpoch.current++;setFolder(null);setDetail(null);setMyFolders([]);setMySets([]);setForm(null);setEdit(null);setMenu(null);setImportTarget(null);setError('');}userRef.current=id;setUserId(id);}),[]);
  useEffect(()=>{if(queueWasRunning.current&&!queue.running)reload();queueWasRunning.current=queue.running;},[queue.running]);
  useEffect(()=>{
    const epoch=++requestEpoch.current;setError('');setLoading(true);if(!props.mine&&!props.folderId&&!props.setId&&offset===0){setFolders([]);setSets([]);}
    const timer=setTimeout(()=>{void(async()=>{
      if(props.folderId){setDetail(null);const value=await readPublicFolder(props.folderId);if(epoch!==requestEpoch.current)return;setFolder(value);}
      else if(props.setId){setFolder(null);const value=await getSharedProblemSet(props.setId);if(epoch!==requestEpoch.current)return;setDetail({...value,standalonePublic:value.visibility==='public',tags:[value.subject,value.audience].filter(Boolean)});}
      else if(props.mine){setFolder(null);setDetail(null);if(userId){const mine=await readMyPublicLibrary(userId);if(epoch!==requestEpoch.current)return;setMyFolders(mine.folders);setMySets(mine.sets);}}
      else {setFolder(null);setDetail(null);const result=await searchPublicLibrary(query,filters,offset);if(epoch!==requestEpoch.current)return;setCategories(result.categories);setMore((filters.kind!=='set'&&result.folders.length>30)||(filters.kind!=='folder'&&result.sets.length>30));setFolders(previous=>[...new Map((offset?[...previous,...result.folders.slice(0,30)]:result.folders.slice(0,30)).map(folder=>[folder.id,folder])).values()]);setSets(previous=>uniquePublicSets(offset?[...previous,...result.sets.slice(0,30)]:result.sets.slice(0,30)));}
    })().catch(reason=>{if(epoch===requestEpoch.current)setError(reason instanceof Error?reason.message:'読み込めませんでした。');}).finally(()=>{if(epoch===requestEpoch.current)setLoading(false);});},props.mine||props.folderId||props.setId?0:200);
    return()=>{clearTimeout(timer);requestEpoch.current++;};
  },[props.folderId,props.setId,props.mine,query,filters,offset,refresh,userId]);
  const act=async(operation:()=>Promise<void>)=>{if(lock.current)return;lock.current=true;setBusy(true);setError('');const viewer=userRef.current;try{await operation();if(viewer===userRef.current)reload();}catch(reason){setError(reason instanceof Error?reason.message:'処理できませんでした。');}finally{lock.current=false;setBusy(false);}};
  const openPublish=(kind:'folder'|'set',destination?:PublicFolder)=>{setPublishChoice(false);if(!userId){props.onLogin();return;}setForm({kind,localId:'',category:'',description:'',tags:'',destination});};
  const submitPublish=()=>act(async()=>{
    if(!form||!userId||!form.localId||!form.category.trim())return;
    const viewEpoch=requestEpoch.current;
    const author=await getCloudDisplayName();if(userId!==userRef.current)throw new Error('アカウントが変更されています。');
    const root=form.kind==='folder'?data.folders.find(f=>f.id===form.localId):undefined;
    const subtree=root?folderSubtreeIds(data.folders,root.id):null;
    const chosen=subtree?data.problemSets.filter(s=>subtree.has(s.folderId)):data.problemSets.filter(s=>s.id===form.localId);
    if(!chosen.length)throw new Error('公開できる問題セットがありません。');
    let destination=form.destination;
    if(root){const id=await managePublicFolder(userId,'save',undefined,{local_folder_id:root.id,name:root.name,description:form.description,category:form.category,tags:form.tags.split(/[,、]/).map(tag=>tag.trim()).filter(Boolean),pending_set_ids:chosen.map(s=>s.id)});destination={id} as PublicFolder;}
    const questionsBySet=new Map<string,AppData['questions']>();for(const question of data.questions){const rows=questionsBySet.get(question.setId)??[];rows.push(question);questionsBySet.set(question.setId,rows);}
    const rows=chosen.map(set=>{try{const payload=prepareLocalPublication({data:{...data,problemSets:[set],questions:questionsBySet.get(set.id)??[]},setId:set.id,visibility:destination?'link':'public',keepVisibility:!!destination,addDestinations:true,authorName:author,publicationInfo:{audience:set.audience?.trim()||form.category,description:root||destination?set.description??'':form.description}});if(!destination)payload.p_set.subject=form.category;
      const child=root&&set.folderId!==root.id?data.folders.find(f=>f.id===set.folderId):undefined;return {payload,publicFolderId:destination?.id,publicFolderPath:child?[{id:child.id,name:child.name}]:[]};}catch(reason){return {payload:{p_set:{local_set_id:set.id,title:set.title},p_questions:[]},publicFolderId:destination?.id,preparationError:reason instanceof Error?reason.message:'公開内容を確認できません。'};}});
    await queue.enqueue(rows);setForm(null);if(viewEpoch===requestEpoch.current&&(!props.mine||props.folderId||props.setId))props.onMine();
  });
  const withdraw=(item:PublicFolder|PublicSet)=>setConfirmation({label:`「${'name' in item?item.name:item.title}」の${'name' in item?'フォルダ公開':'単独公開'}を解除しますか？`,run:async()=>{if('name' in item){await queue.cancelForFolder(item.id);await managePublicFolder(userId,'unpublish',item.id);}else {const localId=data.problemSets.find(set=>set.cloudSetId===item.id)?.id||queue.jobs.find(job=>job.result?.id===item.id)?.localSetId||item.localSetId;await queue.cancelForSet(localId);const result=await setStandalonePublic(userId,item.id,false);const local=data.problemSets.find(s=>s.cloudSetId===item.id);if(local)await props.onPublished(local.id,result);}setConfirmation(null);setMenu(null);}});
  const openImport=(item:PublicFolder|PublicSet)=>{setError('');setImportTarget(item);setTargetFolder(data.folders[0]?.id??'');setNewFolderName('name' in item?item.name:'取り込んだ教材');};
  const submitImport=()=>act(async()=>{
    if(!importTarget)return;const viewer=userRef.current,viewEpoch=requestEpoch.current;
    let source:PublicSet[],options:Parameters<typeof planPublicImport>[2];
    if('name' in importTarget){const complete=await fullPublicFolder(importTarget);source=complete.members??[];options={folder:complete,newFolderName};}
    else {const value=await getSharedProblemSet(importTarget.id);source=[{...importTarget,...value}];options={targetId:targetFolder||undefined,newFolderName};}
    if(viewer!==userRef.current||((await getCloudSession())?.user.id??'')!==viewer)throw new Error('アカウントが変更されています。');
    if(viewEpoch!==requestEpoch.current)return;
    const result=await props.onImport(source,options);setImportTarget(null);
    let statsFailure=false;if(viewer)for(const item of result.imported)try{await recordPublicImport(viewer,item.cloudId,item.localId);}catch{statsFailure=true;}
    if(statsFailure){setNotice('取り込みは保存済みです。取り込み人数の反映は確認できませんでした。');reload();return;}
    if(viewEpoch===requestEpoch.current&&result.imported[0])props.onOpenLocalSet(result.imported[0].localId);
  });
  const owner=(item:PublicFolder|PublicSet)=>!!userId&&item.ownerId===userId;
  const actions=(item:PublicFolder|PublicSet)=><button type="button" className="public-more" disabled={busy} aria-label={`${'name' in item?item.name:item.title}の公開メニュー`} onClick={()=>setMenu(item)}><svg viewBox="0 0 24 24" width="24" height="24" aria-hidden="true" fill="currentColor"><circle cx="4" cy="12" r="2"/><circle cx="12" cy="12" r="2"/><circle cx="20" cy="12" r="2"/></svg></button>;
  const title=props.folderId?folder?.name??props.routeTitle??'公開フォルダ':props.setId?detail?.title??props.routeTitle??'問題セット':props.mine?'自分の公開':'見つける';
  const updateFilter=(value:PublicFilters)=>{setOffset(0);setFilters(value);};
  const sortedMembers=[...(folder?.members??[])].sort((a,b)=>memberSort==='popular'?(b.importCount??0)-(a.importCount??0):memberSort==='updated'?b.updatedAt.localeCompare(a.updatedAt):b.publishedAt.localeCompare(a.publishedAt));
  return <Layout><div ref={screenRoot} className="public-screen"><header className={`public-header${!props.mine&&!props.folderId&&!props.setId?' public-header--home':''}`}>
    {props.mine||props.folderId||props.setId?<BackButton onClick={props.onBack} label="戻る" disabled={busy}/>:null}<h1>{title}</h1>{folder&&owner(folder)?actions(folder):detail&&owner(detail)?actions(detail):!props.mine&&!props.folderId&&!props.setId?<button type="button" className="public-text" onClick={props.onMine}>自分の公開 <ChevronRightIcon size={17}/></button>:<span/>}</header>
    {error?<div role="alert" className="public-error">{error}<button type="button" onClick={reload}>再読み込み</button></div>:null}{notice?<p role="status">{notice}</p>:null}{queue.error?<p role="alert">{queue.error}</p>:null}{loading?<p className="public-loading" role="status">読み込み中…</p>:null}
    {loading&&(props.folderId||props.setId)?<div className="public-detail-loading" aria-hidden="true"><LibraryArtwork folder={Boolean(props.folderId)}/><span><i/><i/></span></div>:null}
    {props.folderId&&folder&&!loading?<><div className="public-detail-top"><LibraryArtwork folder/><div><h2>{folder.name}</h2><p>{folder.authorName}</p></div></div><p className="public-description">{folder.description}</p><LibraryTags tags={[folder.category,...folder.tags]}/><LibraryCounts questions={folder.questionCount} sets={folder.setCount} people={folder.importCount}/><button type="button" className="public-primary public-import" disabled={busy||!folder.setCount} onClick={()=>openImport(folder)}>このフォルダを取り込む</button><div className="public-section-heading"><h2>含まれる問題セット</h2><select aria-label="フォルダ内の並び順" value={memberSort} onChange={event=>setMemberSort(event.target.value as typeof memberSort)}><option value="new">新しい順</option><option value="updated">更新順</option><option value="popular">人気順</option></select></div>{owner(folder)?<button type="button" className="public-secondary" disabled={busy} onClick={()=>openPublish('set',folder)}>問題セットを追加</button>:null}{sortedMembers.map(set=><PublicLibraryRow key={set.id} item={set} onOpen={()=>props.onSet(set.id,set.title)} actions={owner(folder)?<button type="button" className="public-more" disabled={busy} aria-label={`${set.title}をフォルダから削除`} onClick={()=>setConfirmation({label:`「${set.title}」をこのフォルダから外しますか？`,run:async()=>{await managePublicFolder(userId,'remove',folder.id,undefined,set.id);setConfirmation(null);}})}>外す</button>:undefined}/>)}{!folder.setCount?<GroupEmpty>問題セットはまだありません。</GroupEmpty>:null}</>:props.setId&&detail&&!loading?<><div className="public-detail-top"><LibraryArtwork/><div><p>{detail.authorName}</p><LibraryTags tags={detail.tags}/><LibraryCounts questions={detail.questionCount} people={detail.importCount}/></div></div><button type="button" className="public-primary public-import" disabled={busy} onClick={()=>openImport(detail)}>この問題セットを取り込む</button>{detail.description?<section className="public-about"><h2>説明</h2><p>{detail.description}</p></section>:null}<SharedQuestionPreview key={detail.id} questions={detail.questions??[]}/></>:props.mine?<>
      <div className="public-segments" role="tablist" aria-label="自分の公開の種類">{(['folder','set'] as const).map(kind=><button type="button" role="tab" aria-selected={mineKind===kind} key={kind} onClick={()=>setMineKind(kind)}>{kind==='folder'?'フォルダ':'問題セット'}</button>)}</div>
      {!userId?<div className="public-empty"><p>公開を管理するにはログインしてください。</p><button type="button" className="public-primary" onClick={props.onLogin}>設定でログイン</button></div>:<>{mineKind==='folder'?myFolders.map(f=><div key={f.id}><PublicLibraryRow simple item={f} onOpen={()=>props.onFolder(f.id,f.name)} actions={actions(f)}/>{!f.published?<small className="public-draft">非公開</small>:null}</div>):mySets.filter(s=>s.standalonePublic).map(s=><PublicLibraryRow simple key={s.id} item={s} onOpen={()=>props.onSet(s.id,s.title)} actions={actions(s)}/>)}{!loading&&(mineKind==='folder'?!myFolders.length:!mySets.some(s=>s.standalonePublic))?<GroupEmpty>公開中の{mineKind==='folder'?'フォルダ':'問題セット'}はありません。</GroupEmpty>:null}<PublicationJobs jobs={queue.jobs.slice(-10)} onRetry={id=>void queue.retry(id)}/><button type="button" className="public-publish-fab" disabled={busy||!cloudConfigured} onClick={()=>setPublishChoice(true)}>＋ 公開する</button></>}
    </>:!props.folderId&&!props.setId?<>
      <div className="public-search"><label><SearchIcon size={21}/><input type="search" value={query} placeholder="フォルダ・問題セットを検索" aria-label="フォルダ・問題セットを検索" onChange={event=>{setOffset(0);setQuery(event.target.value);}}/></label><button type="button" aria-label="検索条件" aria-haspopup="dialog" aria-pressed={filters.category!==''||filters.minimum!==0||filters.maximum!==null||filters.sort!=='popular'} onClick={()=>setDraft({...filters})}><svg viewBox="0 0 24 24" width="22" height="22" fill="none" stroke="currentColor" strokeWidth="1.6" aria-hidden="true"><path d="M3 6h18M3 12h18M3 18h18"/><circle cx="8" cy="6" r="2" fill="white"/><circle cx="16" cy="12" r="2" fill="white"/><circle cx="10" cy="18" r="2" fill="white"/></svg>条件</button></div>
      <div className="public-segments" role="tablist" aria-label="公開の種類">{(['all','folder','set'] as const).map(kind=><button type="button" role="tab" aria-selected={filters.kind===kind} key={kind} onClick={()=>updateFilter({...filters,kind})}>{kind==='all'?'すべて':kind==='folder'?'フォルダ':'問題セット'}</button>)}</div>
      {filters.kind!=='set'?<section><div className="public-section-heading"><h2>{filters.kind==='all'&&filters.sort==='popular'?'人気のフォルダ':'公開フォルダ'}</h2>{filters.kind==='all'?<button type="button" className="public-text" onClick={()=>updateFilter({...filters,kind:'folder'})}>すべて見る <ChevronRightIcon size={17}/></button>:null}</div>{folders.slice(0,filters.kind==='all'?3:undefined).map(f=><PublicLibraryRow key={f.id} item={f} onOpen={()=>props.onFolder(f.id,f.name)}/>)}{!loading&&!error&&!folders.length?<GroupEmpty>条件に合うフォルダはありません。</GroupEmpty>:null}</section>:null}
      {filters.kind!=='folder'?<section><div className="public-section-heading"><h2>{filters.kind==='all'&&filters.sort==='popular'?'人気の問題セット':'公開問題セット'}</h2>{filters.kind==='all'?<button type="button" className="public-text" onClick={()=>updateFilter({...filters,kind:'set'})}>すべて見る <ChevronRightIcon size={17}/></button>:null}</div>{sets.slice(0,filters.kind==='all'?3:undefined).map(s=><PublicLibraryRow key={s.id} item={s} onOpen={()=>props.onSet(s.id,s.title)}/>)}{!loading&&!error&&!sets.length?<GroupEmpty>条件に合う問題セットはありません。</GroupEmpty>:null}</section>:null}{more&&filters.kind!=='all'?<button type="button" className="public-secondary" disabled={loading} onClick={()=>setOffset(n=>n+30)}>もっと見る</button>:null}
    </>:null}
    {draft?<PublicDialog title="検索条件" onClose={()=>setDraft(null)}><div className="public-form"><label>種類<select aria-label="種類" value={draft.kind} onChange={e=>setDraft({...draft,kind:e.target.value as PublicFilters['kind']})}><option value="all">すべて</option><option value="folder">フォルダ</option><option value="set">問題セット</option></select></label><label>カテゴリー<select aria-label="カテゴリー" value={draft.category} onChange={e=>setDraft({...draft,category:e.target.value})}><option value="">指定しない</option>{categories.map(category=><option key={category}>{category}</option>)}</select></label><div className="public-range"><label>最小問題数<input type="number" min="0" value={draft.minimum} onChange={e=>setDraft({...draft,minimum:Math.max(0,Number(e.target.value))})}/></label><label>最大問題数<input type="number" min="0" value={draft.maximum??''} onChange={e=>setDraft({...draft,maximum:e.target.value===''?null:Math.max(0,Number(e.target.value))})}/></label></div><label>並び順<select aria-label="並び順" value={draft.sort} onChange={e=>setDraft({...draft,sort:e.target.value as PublicFilters['sort']})}><option value="popular">人気順</option><option value="new">新着順</option><option value="updated">更新順</option></select></label><button type="button" className="public-secondary" onClick={()=>setDraft({...initialPublicFilters})}>条件をクリア</button><button type="button" className="public-primary" disabled={!Number.isSafeInteger(draft.minimum)||draft.maximum!==null&&(!Number.isSafeInteger(draft.maximum)||draft.maximum<draft.minimum)} onClick={()=>{updateFilter(draft);setDraft(null);}}>この条件で検索</button></div></PublicDialog>:null}
    {publishChoice?<PublicDialog title="公開するものを選択" onClose={()=>setPublishChoice(false)}><div className="public-form"><button type="button" className="public-secondary" onClick={()=>openPublish('folder')}>フォルダを公開</button><button type="button" className="public-secondary" onClick={()=>openPublish('set')}>問題セットを公開</button></div></PublicDialog>:null}
    {form?<PublicDialog title={form.destination?'フォルダに問題セットを追加':form.kind==='folder'?'フォルダを公開':'問題セットを公開'} busy={busy} onClose={()=>setForm(null)}><div className="public-form"><label>{form.kind==='folder'?'公開するフォルダ':'公開する問題セット'}<select aria-label={form.kind==='folder'?'公開するフォルダ':'公開する問題セット'} value={form.localId} onChange={e=>{const set=data.problemSets.find(s=>s.id===e.target.value);setForm({...form,localId:e.target.value,category:set?.subject||set?.audience||form.category,description:form.kind==='set'?set?.description??'':form.description});}}><option value="">選択してください</option>{(form.kind==='folder'?data.folders:data.problemSets).map(item=><option key={item.id} value={item.id}>{'name' in item?item.name:item.title}</option>)}</select></label><label>カテゴリー・用途<input maxLength={80} value={form.category} onChange={e=>setForm({...form,category:e.target.value})}/></label>{!form.destination?<label>説明<textarea maxLength={form.kind==='folder'?1000:300} value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label>:null}{form.kind==='folder'?<label>タグ（カンマ区切り）<input value={form.tags} onChange={e=>setForm({...form,tags:e.target.value})}/></label>:null}{error?<p role="alert">{error}</p>:null}<button type="button" className="public-primary" disabled={busy||!form.localId||!form.category.trim()} onClick={submitPublish}>{busy?'保存中…':form.destination?'このフォルダに追加':'公開する'}</button></div></PublicDialog>:null}
    {menu?<PublicDialog title="公開の管理" onClose={()=>setMenu(null)}><div className="public-form"><strong>{'name' in menu?menu.name:menu.title}</strong><button type="button" className="public-secondary" onClick={()=>{const item=menu;setMenu(null);if('name' in item)props.onFolder(item.id,item.name);else props.onSet(item.id,item.title);}}>公開内容を確認</button>{'name' in menu?<><button type="button" className="public-secondary" onClick={()=>{setEditTags(menu.tags.join(", "));setEdit(menu);setMenu(null);}}>フォルダ情報を編集</button><button type="button" className="public-secondary" onClick={()=>{const item=menu;setMenu(null);openPublish('set',item);}}>問題セットを追加</button>{!menu.published?<button type="button" className="public-primary" onClick={()=>void act(async()=>{await managePublicFolder(userId,'publish',menu.id);setMenu(null);} )}>公開を再開</button>:null}</>:null}{!('name' in menu)&&!menu.standalonePublic?<button type="button" className="public-primary" onClick={()=>void act(async()=>{const result=await setStandalonePublic(userId,menu.id,true);const local=data.problemSets.find(set=>set.cloudSetId===menu.id);if(local)await props.onPublished(local.id,result);setMenu(null);})}>このセットを単独公開</button>:null}<button type="button" className="public-danger" onClick={()=>{const item=menu;setMenu(null);withdraw(item);}}>公開解除</button></div></PublicDialog>:null}
    {edit?<PublicDialog title="フォルダ情報を編集" busy={busy} onClose={()=>setEdit(null)}><div className="public-form"><label>フォルダ名<input maxLength={100} value={edit.name} onChange={e=>setEdit({...edit,name:e.target.value})}/></label><label>説明<textarea maxLength={1000} value={edit.description} onChange={e=>setEdit({...edit,description:e.target.value})}/></label><label>カテゴリー<input maxLength={80} value={edit.category} onChange={e=>setEdit({...edit,category:e.target.value})}/></label><label>タグ<input value={editTags} onChange={e=>setEditTags(e.target.value)}/></label><button type="button" className="public-primary" disabled={busy||!edit.name.trim()} onClick={()=>void act(async()=>{await managePublicFolder(userId,'save',edit.id,{local_folder_id:edit.localFolderId,name:edit.name,description:edit.description,category:edit.category,tags:editTags.split(/[,、]/).map(tag=>tag.trim()).filter(Boolean)});setEdit(null);})}>保存する</button></div></PublicDialog>:null}
    {confirmation?<PublicDialog title="公開設定の確認" busy={busy} onClose={()=>setConfirmation(null)}><div className="public-form"><p>{confirmation.label}</p><button type="button" className="public-danger" disabled={busy} onClick={()=>void act(confirmation.run)}>実行する</button></div></PublicDialog>:null}
    {importTarget?<PublicDialog title="取り込み先を選択" busy={busy} onClose={()=>setImportTarget(null)}><div className="public-form"><strong>{'name' in importTarget?importTarget.name:importTarget.title}</strong>{'name' in importTarget?<p>フォルダごとホームに取り込みます。</p>:<label>取り込み先<select aria-label="取り込み先" value={targetFolder} onChange={e=>setTargetFolder(e.target.value)}><option value="">新しいフォルダを作成</option>{data.folders.map(f=><option key={f.id} value={f.id}>{f.name}</option>)}</select></label>}{'name' in importTarget||!targetFolder?<label>フォルダ名<input maxLength={100} value={newFolderName} onChange={e=>setNewFolderName(e.target.value)}/></label>:null}{!('name' in importTarget)&&data.problemSets.some(s=>s.sourceSetId===importTarget.id&&s.sourceVersionId===importTarget.versionId)?<p>取り込み済みです。同じ保存先の未編集コピーは再利用します。</p>:null}{error?<p role="alert">{error}</p>:null}<button type="button" className="public-primary" disabled={busy||(('name' in importTarget||!targetFolder)&&!newFolderName.trim())} onClick={submitImport}>{busy?'取り込み中…':'ここに取り込む'}</button></div></PublicDialog>:null}
  </div></Layout>;
}
