import {publicLibraryRpc,mapProblemSetRow,getSharedProblemSet,getInstallationId,type CloudPublishResult} from './cloudService';
import type {PublicFolder,PublicSet,PublicFilters} from './publicLibrary';
import {publicFilterArgs} from './publicLibrary';
export function parsePublicSet(row:Record<string,unknown>):PublicSet{return {...mapProblemSetRow(row),versionId:typeof row.version_id==='string'?row.version_id:undefined,standalonePublic:row.standalone_public===true,tags:Array.isArray(row.tags)?row.tags.map(String):[],memberPath:Array.isArray(row.member_path)?row.member_path as PublicSet['memberPath']:undefined};}
export function parsePublicFolder(row:Record<string,unknown>):PublicFolder{return {id:String(row.id),ownerId:String(row.owner_id),localFolderId:typeof row.local_folder_id==='string'?row.local_folder_id:undefined,name:String(row.name),description:String(row.description??''),category:String(row.category??''),tags:Array.isArray(row.tags)?row.tags.map(String):[],authorName:String(row.author_name??''),published:row.published===true,setCount:Number(row.set_count),questionCount:Number(row.question_count),importCount:Number(row.import_count),updatedAt:String(row.updated_at),members:Array.isArray(row.members)?row.members.map(item=>parsePublicSet(item as Record<string,unknown>)):undefined};}
export async function searchPublicLibrary(query:string,filters:PublicFilters,offset=0){const row=await publicLibraryRpc('quiz_public_search',publicFilterArgs(query,filters,offset)) as Record<string,unknown>;if(!row||!Array.isArray(row.folders)||!Array.isArray(row.sets)||!Array.isArray(row.categories))throw new Error('公開一覧を確認できません。');return {folders:row.folders.map(item=>parsePublicFolder(item as Record<string,unknown>)),sets:row.sets.map(item=>parsePublicSet(item as Record<string,unknown>)),categories:row.categories.map(String)};}
export async function readPublicFolder(id:string){return parsePublicFolder(await publicLibraryRpc('quiz_public_folder',{p_id:id}) as Record<string,unknown>);}
export async function readMyPublicLibrary(userId:string){const row=await publicLibraryRpc('quiz_public_mine',{},userId) as Record<string,unknown>;return {folders:(row.folders as Record<string,unknown>[]).map(parsePublicFolder),sets:(row.sets as Record<string,unknown>[]).map(parsePublicSet)};}
export async function managePublicFolder(userId:string,action:string,id?:string,metadata?:Record<string,unknown>,setId?:string,path?:unknown){return String(await publicLibraryRpc('quiz_public_folder_manage',{p_action:action,p_id:id??null,p_meta:metadata??{},p_set_id:setId??null,p_path:path??[]},userId));}
export async function setStandalonePublic(userId:string,id:string,value:boolean):Promise<CloudPublishResult>{const row=await publicLibraryRpc('quiz_public_set_visibility',{p_id:id,p_public:value},userId) as Record<string,unknown>;return {id:String(row.id),shareToken:String(row.share_token),versionId:typeof row.version_id==='string'?row.version_id:undefined,visibility:row.visibility as CloudPublishResult['visibility']};}
export async function recordPublicImport(userId:string,id:string,localId:string){await publicLibraryRpc('quiz_public_record_import',{p_id:id,p_installation:getInstallationId(),p_local_id:localId},userId);}
export async function fullPublicFolder(folder:PublicFolder){const latest=await readPublicFolder(folder.id),sets=[];for(const member of latest.members??[]){const detail=await getSharedProblemSet(member.id);if(detail.versionId!==member.versionId||detail.updatedAt!==member.updatedAt)throw new Error('公開内容が更新されました。もう一度取り込んでください。');sets.push({...member,...detail});}const final=await readPublicFolder(folder.id);if(final.updatedAt!==latest.updatedAt||JSON.stringify(final.members?.map(set=>[set.id,set.versionId,set.updatedAt]))!==JSON.stringify(latest.members?.map(set=>[set.id,set.versionId,set.updatedAt])))throw new Error('フォルダ内容が更新されました。もう一度取り込んでください。');return {...latest,members:sets};}
